2025-01-12 23:34:29,234 - ERROR - admin_actions - Line: 46 - Error in add_user: 'list' object has no attribute 'values'
2025-01-12 23:36:00,502 - ERROR - admin_actions - Line: 46 - Error in add_user: 'list' object has no attribute 'values'
2025-01-12 23:37:32,802 - ERROR - admin_actions - Line: 46 - Error in add_user: 'list' object has no attribute 'values'
2025-01-12 23:39:13,868 - ERROR - admin_actions - Line: 46 - Error in add_user: 'list' object has no attribute 'values'
2025-01-13 22:00:29,518 - ERROR - admin_actions - Line: 188 - Error in delete_user: 'id'
2025-01-13 22:01:26,902 - ERROR - admin_actions - Line: 188 - Error in delete_user: 'id'
2025-01-13 22:09:55,033 - ERROR - admin_actions - Line: 148 - Error in update_user: 'id'
2025-01-15 17:18:53,052 - ERROR - admin_actions - Line: 212 - Error in list_cars: unsupported format string passed to NoneType.__format__
2025-01-15 17:21:47,242 - ERROR - admin_actions - Line: 212 - Error in list_cars: unsupported format string passed to NoneType.__format__
2025-01-17 11:36:50,541 - ERROR - admin_actions - Line: 358 - Error in update_car: AdminDatabaseHandler.update_car() got an unexpected keyword argument 'owner_id'. Did you mean 'user_id'?
2025-01-17 15:59:48,024 - ERROR - admin_actions - Line: 484 - Error in add_service: expected string or bytes-like object, got 'NoneType'
2025-01-17 16:22:37,534 - ERROR - login_module - Line: 61 - Error logging in: 'NoneType' object has no attribute 'get'
2025-01-17 16:28:18,600 - INFO - login_module - Line: 51 - User testtest logged in successfully as user.
2025-01-18 23:42:52,401 - ERROR - admin_actions - Line: 573 - Error in update_service: Python type dict_values cannot be converted
2025-01-19 11:48:41,327 - ERROR - admin_actions - Line: 573 - Error in update_service: Python type dict_values cannot be converted
2025-01-20 13:07:42,457 - ERROR - user_actions - Line: 168 - Error in add_car: 'count'
